# src/personas.py

from openai import OpenAI
from config import LLM_API_KEY, LLM_MODEL, PERSONA_ARCHETYPES

client = OpenAI(api_key=LLM_API_KEY)

def generate_personas(context, archetypes, num_personas, event_callback=None):
    """
    Generates synthetic personas for a given context using an LLM.
    """
    personas = []
    for i in range(num_personas):
        archetype_key = archetypes[i % len(archetypes)]
        archetype_details = PERSONA_ARCHETYPES[archetype_key]

        system_prompt = f"""
        Eres un generador de perfiles de personas realistas que podrían estar presentes en el contexto provisto.
        
        **INSTRUCCIONES IMPORTANTES:**
        
        - Genera perfiles detallados y realistas basados en el contexto específico
        - Evita nombres genéricos (John Doe, Jane Smith) y empresas ficticias (ABC Corp, XYZ Inc)
        - Usa nombres reales de empresas existentes cuando sea apropiado
        - Asegúrate de que cada perfil sea coherente internamente (edad vs experiencia, posición vs tamaño de empresa, etc.)
        - Varía los perfiles para representar diversidad en roles, industrias y backgrounds
        
        **FORMATO REQUERIDO:**

        Company: [Nombre de empresa real y específica]
        Name: [Nombre Apellido realista]
        Gender: [Male/Female/Non-binary]
        Age: [Edad específica]
        Profession: [Profesión específica]
        Current Position: [Título exacto del puesto]
        Location: [Ciudad, País]
        Years of Experience: [Número específico]
        Company Size: [Número de empleados]
        Company ARR: [Revenue usando K, M o B; e.g.: 10M]
        Team Size: [Número de personas en su equipo]
        Industry: [Industria específica]
        Education: [Universidad y grado]
        Key Skills: [3-5 habilidades principales]
        Interests: [3-5 intereses específicos]
        LinkedIn Summary: [Breve descripción de 1-2 líneas]
        
        """

        prompt = f"""
        Genera un perfil de persona para el arquetipo '{archetype_key}' ({archetype_details['description']}) en la industria de '{context['industry']}' en '{context['location']}'.
        
        Considera el sesgo psicológico de este arquetipo: {archetype_details['bias']}.
        """
        
        try:
            response = client.chat.completions.create(
                model=LLM_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.8,
            )
            
            persona_text = response.choices[0].message.content
            persona_data = parse_persona_data(persona_text)
            persona_data['archetype'] = archetype_key
            personas.append(persona_data)

            if event_callback:
                event_callback("persona_created", {
                    "index": i,
                    "total": num_personas,
                    "persona": persona_data,
                })

        except Exception as e:
            print(f"Error al generar persona: {e}")
            continue
            
    return personas

def parse_persona_data(persona_text):
    """
    Parses the text generated by the LLM into a structured profile.
    """
    profile = {}
    lines = persona_text.split('\n')
    key_mapping = {
        "Company": "company",
        "Name": "name",
        "Gender": "gender",
        "Age": "age",
        "Profession": "profession",
        "Current Position": "title",
        "Location": "location",
        "Years of Experience": "years_of_experience",
        "Company Size": "company_size",
        "Company ARR": "company_arr",
        "Team Size": "team_size",
        "Industry": "industry",
        "Education": "education",
        "Key Skills": "key_skills",
        "Interests": "interests",
        "LinkedIn Summary": "linkedin_summary"
    }
    for line in lines:
        for key, profile_key in key_mapping.items():
            if f"{key}:" in line:
                profile[profile_key] = line.split(f"{key}:", 1)[1].strip()
    return profile


if __name__ == "__main__":
    import argparse
    import json
    import os

    parser = argparse.ArgumentParser(description="Stage 2: Generate synthetic personas")
    parser.add_argument("--input", default="data/fixtures/context.json",
                        help="Path to context JSON (default: data/fixtures/context.json)")
    parser.add_argument("--output", default="data/outputs/personas_output.json",
                        help="Path to write the output JSON (default: data/outputs/personas_output.json)")
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        context = json.load(f)

    archetypes = list(PERSONA_ARCHETYPES.keys())
    print(f"Generating {len(archetypes)} personas for: {context['industry']} in {context['location']}")
    personas = generate_personas(context, archetypes, len(archetypes))

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(personas, f, ensure_ascii=False, indent=2)

    print(f"\nGenerated {len(personas)} personas:")
    for p in personas:
        print(f"  - {p.get('name')} ({p.get('archetype')}) @ {p.get('company')}")
    print(f"\n✓ Output saved to {args.output}")
