# src/personas.py

from openai import OpenAI
from config import LLM_API_KEY, LLM_MODEL, PERSONA_ARCHETYPES

client = OpenAI(api_key=LLM_API_KEY)

def generate_personas(niche, archetypes, num_personas):
    """
    Generates synthetic personas for a given industry niche using an LLM.
    """
    personas = []
    for i in range(num_personas):
        archetype_key = archetypes[i % len(archetypes)]
        archetype_details = PERSONA_ARCHETYPES[archetype_key]

        prompt = f"""
        Eres un generador de perfiles de expertos para una simulación de mercado.
        Crea un perfil detallado para un profesional en la industria de '{niche}'.

        Arquetipo: {archetype_key}
        Descripción del Arquetipo: {archetype_details['description']}
        Sesgo Psicológico: {archetype_details['bias']}

        Genera un nombre ficticio, un puesto de trabajo específico en la industria,
        y una breve biografía (2-3 frases) que refleje su experiencia, su sesgo
        y su rol en el ecosistema de '{niche}'.

        Formato de salida:
        Nombre: [Nombre Completo]
        Puesto: [Puesto de Trabajo]
        Biografía: [Biografía]
        """

        try:
            response = client.chat.completions.create(
                model=LLM_MODEL,
                messages=[
                    {"role": "system", "content": "Eres un generador de perfiles de expertos."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=150,
                n=1,
                stop=None,
                temperature=0.7,
            )
            profile_text = response.choices[0].message.content.strip()

            # Parse the generated text
            profile = parse_profile(profile_text)
            profile['archetype'] = archetype_key
            personas.append(profile)

        except Exception as e:
            print(f"Error al generar persona: {e}")
            # Fallback to a simple persona
            personas.append({
                "name": f"Experto {i+1}",
                "title": f"Consultor en {niche}",
                "bio": "Experto genérico con amplio conocimiento del sector.",
                "archetype": archetype_key
            })

    return personas

def parse_profile(profile_text):
    """
    Parses the text generated by the LLM into a structured profile.
    """
    profile = {}
    lines = profile_text.split('\n')
    for line in lines:
        if "Nombre:" in line:
            profile['name'] = line.split("Nombre:", 1)[1].strip()
        elif "Puesto:" in line:
            profile['title'] = line.split("Puesto:", 1)[1].strip()
        elif "Biografía:" in line:
            profile['bio'] = line.split("Biografía:", 1)[1].strip()
    return profile
